### ISSUE TITLE
Small version

### ISSUE THREAD

**Issue by Porco-Rosso** [louixs/tsushin#1]
Hi, 
Firstly great job with the widget! Looks great.

I'm trying to shrink the graph, to put it at the bottom of my screen, however I haven't been able to make it scale properly.
It seems there is not enough vertical space for the graph to plot correctly. 

<img width="708" alt="screen shot 2016-12-05 at 5 10 20 pm" src="https://cloud.githubusercontent.com/assets/7024527/20892314/fbe60850-bb0d-11e6-91ac-5597bcfae451.png">

Could you maybe point me in the right direction?

**Comment by louixs** [comment]
Hi @Porco-Rosso! 

Thanks a lot for your comment. 
You are right in that it doesn't seem to shrink properly. 
I've tried to implement a smaller, bare-minimum version of the graph (attached).

What I did is to mostly tweak highchart options. 
Note that when I scaled down the chart, it didn't seem to show the y-axis labels correctly so I've disabled them for now. Would it be something you'd want to have? 

You can try to replace tsushin.coffee with the one in your tsushin.widget folder from the attached file to see if that does the job. 

Attachment: 
[tsushin_small.widget.zip](https://github.com/louixs/tsushin/files/632407/tsushin_small.widget.zip)

**Comment by Porco-Rosso** [comment]
thanks for the quick reply, I still had to play around with the positioning, as there was still a bottom margin to the graph, but so far it's looking great!

A Y-axis chart (and x-axis chart), would still be great to have, even if that meant the font-size being barely readable. My display resolution is pretty high, and I would only read it when needed so it's not such a big concern in my case to have a really small font size.
Having a graph without labels to interpret it almost defeats the point of visualising the data. 

Thanks again for taking the time to alter the graph! Here's how it looks now:
<img width="755" alt="screen shot 2016-12-06 at 1 21 32 am" src="https://cloud.githubusercontent.com/assets/7024527/20908058/5dc344c2-bb52-11e6-9508-ecf0a8eb4abf.png">

**Comment by Porco-Rosso** [comment]
also please note that the .sh file path still directs towards `tsushin.widget` and not `tsushin_small.widget`

**Comment by louixs** [comment]
Hi, 

I totally agree with you about the labels! 
I made some corrections and now added the y-axis label for the max value (in kB) as well as timestamps on x-axis. The chart might be a bigger than the size you would like judging from the picture you attached. 
It now looks like this. 
![screen shot 2016-12-06 at 23 46 22](https://cloud.githubusercontent.com/assets/6142340/20948995/f123eb24-bc0e-11e6-873d-38dcedb62ff1.png)

If you need to shrink it even further, try adjusting the following:
Apart from the actual size of the chart as in width and heigh,
fontSizes, and width of the plotLines. Also if you want to get rid of the timestamps on the x-axis, you can change marginBottom to 1 or 0. 

Link to the updated widget:
[Widget](https://github.com/louixs/tsushin/blob/master/tsushin_small.widget.zip)

**Comment by Porco-Rosso** [comment]
Hi,
Works and looks great thanks! 
An off topic question, but do you know how to set the axis colors as partly transparent?
Using `rgba(#fff, .5)` doesn't seem to do the trick.

**Comment by louixs** [comment]
That's a great pleasure to hear! Again, super-thanks for your feedback! 

As for your question about the axis colours, do you mean you want to set it so it's gradient i.e. solid colour on one side to gradually fade into transparency?
Have you got an example screenshot or pic by any chance?

**Comment by Porco-Rosso** [comment]
No problem.
I'm just trying to set a 50% opacity for the white text and line in the screenshot below, like the two widgets to the right.

<img width="638" alt="screen shot 2016-12-07 at 10 42 49 pm" src="https://cloud.githubusercontent.com/assets/7024527/20987853/82327148-bcce-11e6-970e-e747d66a4f0f.png">

**Comment by louixs** [comment]
Right. I think you were almost there.
It seems you were giving hex value for rgba colour.
You would need to covert the colour you would like to use from hex to rgba.
#fff should be `'rgba(255, 15, 0)'` . I just used this [site](http://www.javascripter.net/faq/hextorgb.htm) to convert. 
 
Additionally to set opacity you can add another parameters for instance as below:
` 'rgba(126, 255, 255, 0.50)'`

See [this link](http://stackoverflow.com/questions/24035938/highcharts-change-opacity-of-a-column-chart[](url)).

Hope this is clear enough!

**Comment by Porco-Rosso** [comment]
thanks looking as I'd like now, I've never had to enter rgba colors as hex.

Out of curiosity is it possible to make the highchart graph lines curved as opposed to such jagged angles?

**Comment by louixs** [comment]
I'm glad that you were able to find the styling you liked! It's a bit tricky with css and colors sometimes I know... 
Apologies for delay. As for the curved lines for highchart/highstock you might want to take a look at  [spline](http://www.highcharts.com/stock/demo/spline). 
Let me know if you need any help!

**Comment by Porco-Rosso** [comment]
Adding spline to anywhere but at the end of this section seems to cause an error in ubersicht

    series: [ {
      name: 'Down (kB)'
      lineWidth: 1
      color: '#9659B2'
      data: []
      },
      {
       name: "Up (kB)"
       lineWidth: 1
       color:'#4EA565'
       data:[]
        }
    type: 'spline']
    credits:
      enabled: false

But it seems to have no effect. Does the type of graph have to be changed?
